CREATE TABLE [metadata].[pipeline_control] (

	[control_id] bigint IDENTITY NOT NULL, 
	[layer] varchar(10) NOT NULL, 
	[domain] varchar(30) NOT NULL, 
	[object_name] varchar(100) NOT NULL, 
	[source_type] varchar(20) NOT NULL, 
	[source_connection_name] varchar(100) NULL, 
	[source_workspace] varchar(100) NULL, 
	[source_lakehouse] varchar(50) NULL, 
	[source_schema] varchar(50) NULL, 
	[source_object_name] varchar(100) NULL, 
	[sql_file_path] varchar(300) NULL, 
	[target_lakehouse] varchar(50) NOT NULL, 
	[target_schema] varchar(50) NOT NULL, 
	[target_table] varchar(100) NOT NULL, 
	[load_type] varchar(20) NOT NULL, 
	[key_columns] varchar(500) NULL, 
	[incremental_column] varchar(128) NULL, 
	[incremental_column_type] varchar(30) NULL, 
	[watermark_value] varchar(50) NULL, 
	[depends_on_control_ids] varchar(500) NULL, 
	[batch_group] int NOT NULL, 
	[is_active] bit NOT NULL, 
	[created_on] datetime2(6) NOT NULL, 
	[updated_on] datetime2(6) NULL, 
	[last_load_status] varchar(20) NULL, 
	[last_load_start_time] datetime2(6) NULL, 
	[last_load_end_time] datetime2(6) NULL, 
	[last_row_count] bigint NULL, 
	[last_error_message] varchar(4000) NULL, 
	[last_run_id] varchar(100) NULL, 
	[last_parent_run_id] varchar(100) NULL, 
	[sql_lakehouse] varchar(50) NULL
);